# Generated by Django 4.1.4 on 2022-12-23 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_odd_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='odd',
            name='anchor',
            field=models.URLField(null=True),
        ),
    ]
