# Generated by Django 4.1.4 on 2022-12-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_plan_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'verbose_name': 'Plano', 'verbose_name_plural': 'Planos'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.RemoveField(
            model_name='odd',
            name='processed',
        ),
        migrations.AlterField(
            model_name='user',
            name='houses',
            field=models.TextField(blank=True, null=True),
        ),
    ]
