# Generated by Django 4.1.5 on 2023-01-12 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Valor'),
        ),
        migrations.AddField(
            model_name='plan',
            name='months',
            field=models.IntegerField(default=1, verbose_name='Meses (carência)'),
        ),
    ]
