# Generated by Django 4.1.5 on 2023-01-21 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_user_referer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='whatsapp',
            field=models.BooleanField(default=False, verbose_name='WhatsApp'),
        ),
    ]
