# Generated by Django 4.1.5 on 2023-01-23 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_user_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='commission_percent',
            field=models.IntegerField(default=1, verbose_name='Porcentagem de comissão'),
        ),
    ]
