# Generated by Django 4.1.5 on 2023-01-23 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_plan_commission_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odd',
            name='house',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='odd',
            name='match',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='odd',
            name='sport',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='odd',
            name='surebet_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='odd',
            name='tournament',
            field=models.CharField(max_length=255),
        ),
    ]
