# Generated by Django 4.1.5 on 2023-01-26 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='identifier',
            field=models.CharField(editable=False, max_length=255, verbose_name='Identificador Único'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='response',
            field=models.TextField(editable=False, verbose_name='Resposta'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('APPROVED', 'Aprovado'), ('EXPIRED', 'Expirado')], default='PENDING', editable=False, max_length=100, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('SUBSCRIPTION', 'Assinatura Cartão'), ('PIX', 'Pix')], editable=False, max_length=100, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='webhook_data',
            field=models.TextField(editable=False, null=True, verbose_name='Dados do Webhook'),
        ),
    ]
