# Generated by Django 4.1.5 on 2023-02-04 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_user_time_alter_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='time',
            field=models.CharField(default='12h', max_length=100, null=True),
        ),
    ]
