# Generated by Django 4.1.5 on 2023-02-04 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_user_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='time',
            field=models.CharField(default='a', max_length=100, null=True),
        ),
    ]
