# Generated by Django 4.1.5 on 2023-02-04 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_user_last_session_key_alter_user_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='odd',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
