# Generated by Django 4.1.5 on 2023-02-15 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_odd_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sports',
            field=models.TextField(blank=True, null=True),
        ),
    ]
