# Generated by Django 4.1.5 on 2023-06-05 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_user_sports'),
    ]

    operations = [
        migrations.AddField(
            model_name='odd',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
    ]
