# Generated by Django 4.1.5 on 2023-06-05 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_plan_has_live'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='has_live',
            field=models.BooleanField(default=False, help_text='Marque esta opção caso o plano em questão possua o tipo Live de apostas', verbose_name='Possui Live?'),
        ),
    ]
