# Generated by Django 4.1.5 on 2023-06-05 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_plan_has_live'),
    ]

    operations = [
        migrations.AddField(
            model_name='odd',
            name='live_color',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
