# Generated by Django 4.1.5 on 2023-06-05 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_user_plan_expire_alter_payment_plan_and_more'),
        ('core', '0029_plan_live_only'),
    ]

    operations = [
    ]
