# Generated by Django 4.1.5 on 2023-06-06 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_remove_user_plan_expire_alter_odd_match_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odd',
            name='anchor',
            field=models.URLField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='odd',
            name='house',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='odd',
            name='surebet_id',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='odd',
            name='tournament',
            field=models.CharField(max_length=1000),
        ),
    ]
