# Generated by Django 4.2 on 2023-06-10 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_odd_anchor_alter_odd_house_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='plan_expire',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de expiração do plano'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.plan', verbose_name='Plano'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('CARD', 'Cartão'), ('PIX', 'Pix')], max_length=100, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cliente'),
        ),
    ]
