# Generated by Django 4.1.5 on 2023-07-04 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='max_chance',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='Odd máxima'),
        ),
        migrations.AddField(
            model_name='config',
            name='min_chance',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='Odd mínima'),
        ),
        migrations.AlterField(
            model_name='config',
            name='message',
            field=models.TextField(default='➡️NOVA OPORTUNIDADE \n\n🏆 ESPORTE: {esporte}\n🏳️LIGA: {liga}\n🎪EVENTO: {evento}\n⏰HORARIO: {horario}\n📊LUCRO: {lucro}\n📁MERCADO: {mercado}\n\n🏠1° {casa1}\nODD: {odd_casa1}\nLink : {link_casa1}\n\n🏠2° {casa2}\nODD: {odd_casa2}\nLink: {link_casa2}\n\n✅VERIFIQUE O VALOR MÁXIMO QUE AS CASAS DEIXAM APOSTAR\n✅VERIFIQUE SE AS ODDS NÃO MUDARAM\n✅RECOMENDADO: R$ 1000\n✅NÃO USAR VALORES QUEBRADOS NAS ENTRADAS', verbose_name='Mensagem'),
        ),
    ]
